apiVersion: v1
kind: Secret
metadata:
  name: {{ include "karpenter-cloudstack.fullname" . }}-cloudstack
  labels:
    {{- include "karpenter-cloudstack.labels" . | nindent 4 }}
type: Opaque
stringData:
  apiUrl: {{ .Values.cloudstack.apiUrl | quote }}
  apiKey: {{ .Values.cloudstack.apiKey | quote }}
  secretKey: {{ .Values.cloudstack.secretKey | quote }}

