apiVersion: v2
name: karpenter-cloudstack
description: A Helm chart for Karpenter CloudStack Provider
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - karpenter
  - cloudstack
  - autoscaling
  - kubernetes
home: https://github.com/mperea/karpenter-provider-cloudstack
sources:
  - https://github.com/mperea/karpenter-provider-cloudstack
maintainers:
  - name: Mario Perea
    url: https://github.com/mperea

